substitutions:
  name: apollo-rly-1
  version: "25.4.28.1"
  device_description: ${name} made by Apollo Automation - version ${version}.

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  #flash_size: 8MB
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

# Time component required for total_daily_energy
time:
  - platform: homeassistant
    id: homeassistant_time
  - platform: sntp
    id: sntp_time
    timezone: America/New_York
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
    on_time_sync:
      then:
        - logger.log: "Time synchronized with NTP server"
external_components:
  - source: github://PhracturedBlue/c6_adc
    refresh: 0s   # uncomment to force refresh of repo
api:

globals:
  # Voltage setting for power calculations - can be adjusted for different regions
  - id: line_voltage
    type: float
    restore_value: yes
    initial_value: '120.0'

  - id: cycleCounter
    type: int
    restore_value: no
    initial_value: '0'
  - id: button_press_timestamp
    restore_value: no
    type: uint32_t
    initial_value: '0'
  - id: runTest
    restore_value: yes
    type: bool
    initial_value: "true"

captive_portal:

web_server:
  port: 80

one_wire:
  - platform: gpio
    pin: GPIO15

switch:
  - platform: gpio
    name: "Relay"
    pin: GPIO14
    id: relay
  - platform: factory_reset
    id: factory_reset_switch
    internal: true
    
  - platform: template
    name: "Limit Protection"
    id: limit_protection
    icon: mdi:shield
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: "config"
    turn_on_action:
      - logger.log: "Limit protection enabled"
    turn_off_action:
      - logger.log: "Limit protection disabled"

sensor:
  - platform: dallas_temp
    name: "Temperature Probe"
    update_interval: 5s
    id: temp_probe
  - platform: c6_adc
    pin: GPIO2
    name: "Raw ADC"
    update_interval: 1s
    attenuation: 12db
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 10
      - median:
          window_size: 7
          send_every: 5
      - exponential_moving_average:
          alpha: 0.1
          send_every: 1

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  - platform: gpio
    name: Limit Triggered
    id: limit_triggered
    icon: mdi:connection
    pin: 
      number: GPIO5
      mode:
        input: true
        pulldown: True
    filters:
      - invert:
    on_state:
      then:
        - if:
            condition:
              and:
                - binary_sensor.is_on: limit_triggered
                - switch.is_on: limit_protection
            then:
              - switch.turn_off: relay
              - logger.log: "Limit triggered - turning off relay"
  
    
  - platform: gpio
    pin:
      number: GPIO9
      inverted: true
      mode:
        input: true
        pullup: true
    id: reset_button
    on_press:
      then:
        - lambda: |-
            id(button_press_timestamp) = millis();    
    on_release:
      then:
        - lambda: |-
            if (millis() - id(button_press_timestamp) >= 10000) {
              // Remove Wifi
              id(runTest) = true;
              id(factory_reset_switch).turn_on();
            }
            else {
              // StatusCheck
              id(statusCheck).execute();
              delay(3000);
              id(runTest) = true;
              id(testScript).execute();
            }

light:
  - platform: esp32_rmt_led_strip
    id: rgb_light
    name: "RGB Light"
    pin: GPIO3
    default_transition_length: 0s
    chipset: WS2812
    num_leds: 1
    rgb_order: grb
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 0%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 50%
          max_brightness: 100%

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
    

script:
  - id: statusCheck
    then:
      - if:
          condition:
            - lambda: 'return id(ink_ha_connected).state;'
          then:
            - logger.log: "Apollo Automation: Connected To HA"
            - light.turn_on: 
                id: rgb_light
                brightness: 100%
                red: 0%
                green: 0%
                blue: 100%
          else:
            - if:
                condition:
                  - wifi.connected
                then:
                  - logger.log: "Apollo Automation: Connected To Wifi"
                  - light.turn_on: 
                      id: rgb_light
                      brightness: 100%
                      red: 0%
                      green: 100%
                      blue: 0%
                else: 
                  - logger.log: "Apollo Automation: Not Connected To Wifi"
                  - light.turn_on: 
                      id: rgb_light
                      brightness: 100%
                      red: 100%
                      green: 100%
                      blue: 100%  

  - id: testScript
    then:
      if: 
        condition:
          - lambda: "return id(runTest) == true;"
        then:
          - lambda: "id(runTest) = false;"
          - light.turn_on:
              id: rgb_light
              red: 0%
              green: 100%
              blue: 0%
          - delay: 5s
          - light.turn_on:
              id: rgb_light
              red: 0%
              green: 0%
              blue: 0%
          - light.turn_off:
              id: rgb_light
              
  