esphome:
  name: "apollo-rly-1"
  friendly_name: Apollo RLY-1
  comment: Apollo RLY-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.RLY-1"
    version: "${version}"

  min_version: 2025.2.0

dashboard_import:
  package_import_url: github://ApolloAutomation/RLY-1/Integrations/ESPHome/RLY-1_Minimal.yaml
  import_full_config: false

#improv_serial:

#esp32_improv:
#  authorizer: none

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_managed

http_request:
  verify_ssl: true

safe_mode:

web_server:
  port: 80

update:
  - platform: http_request
    id: firmware_update
    name: Firmware Update
    source: https://apolloautomation.github.io/RLY-1/firmware/manifest.json

wifi:
  #id: wifi_1
  #on_connect:
  #  - delay: 5s
  #  - ble.disable:
  #on_disconnect:
  #  - ble.enable:
  ap:
    ssid: "Apollo RLY1 Hotspot"

logger:

packages:
  core: !include Core.yaml
