esphome:
  name: "${name}"
  friendly_name: Apollo RLY-1
  comment: Apollo RLY-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.RLY-1_BLE"
    version: "${version}"

  min_version: 2025.2.0

dashboard_import:
  package_import_url: github://ApolloAutomation/RLY-1/Integrations/ESPHome/RLY-1_BLE.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome

http_request:
  verify_ssl: true

safe_mode:

bluetooth_proxy:
  active: true
esp32_ble_tracker:
  scan_parameters:
    active: false

wifi:
  ap:
    ssid: "Apollo RLY1 Hotspot"

logger:

packages:
  core: !include Core.yaml
