esphome:
  name: "apollo-rly-1-minimal"
  friendly_name: Apollo RLY-1
  comment: Apollo RLY-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  project:
    name: "ApolloAutomation.RLY-1-Minimal"
    version: "${version}"

  min_version: 2025.2.0

dashboard_import:
  package_import_url: github://ApolloAutomation/RLY-1/Integrations/ESPHome/RLY-1_Minimal.yaml
  import_full_config: false

ota:
  - platform: esphome
    id: ota_esphome

safe_mode:

web_server:
  port: 80

wifi:
  id: wifi_1
  ap:
    ssid: "Apollo RLY1 Hotspot"

logger:

packages:
  core: !include Core.yaml
